// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Toaster } from "sonner";
// import { NavigationMenuDemo } from "@/components/demo/navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//       {/* <StickyBanner className="bg-gradient-to-b from-blue-500 to-blue-600">
//         <p className="mx-0 max-w-[90%] text-white drop-shadow-md">
//           Sign up for ConsultEase today and get 3 months FREE on our Premium Plan – packed with advanced features like appointment scheduling, video consultations, patient management, and more.
//         </p>
//       </StickyBanner> */}
//         <NavigationMenuDemo/>
//         <main>{children}</main>
//         <Toaster/>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { NavigationMenuDemo } from "@/components/demo/navbar";
import  { UserProvider } from "@/context/userContext"; // ✅ Add this line

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <UserProvider>
          <NavigationMenuDemo />
          <main>{children}</main>
          <Toaster />
        </UserProvider>
      </body>
    </html>
  );
}

